[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
solc_version = "0.8.20"

optimizer = true
optimizer_runs = 200

fuzz_runs = 256
fuzz_max_rejects = 65536

fork_block_number = 18500000

gas_limit = 9223372036854775807
gas_price = 20000000000

verbosity = 2

[rpc_endpoints]
mainnet = "eth rpc"

[profile.fork]
match_contract = "ForkIntegrationTest"
verbosity = 3
gas_reports = ["*"]

[profile.ci]
fuzz_runs = 128
verbosity = 1
